# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategyceleryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_id', models.IntegerField()),
                ('price_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('adj_close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
