# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategyceleryapp', '0002_daily_price_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='strategy_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_output', models.TextField()),
                ('strategy_error', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
