# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategyceleryapp', '0004_auto_20170220_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_price',
            old_name='symbol_id',
            new_name='symbol',
        ),
    ]
